### ISSUE TITLE
FTP Error 530 when FTP is down

### ISSUE THREAD

**Issue by ThatOdieGuy** [ThatOdieGuy/downspout#28]
My FTP was unable to login, and Downspout reported this error repeatedly. Appears to be when a user has an invalid user/password.

```0|downspou | 2017-06-23T15:27:25.527Z - error: scanCompleteCallback:  Error: 530 Please login with USER and PASS
0|downspou |     at Ftp.parse (/apps/seedbox-sync/htpc/node_modules/jsftp/lib/jsftp.js:253:11)
0|downspou |     at Ftp.parseResponse (/apps/seedbox-sync/htpc/node_modules/jsftp/lib/jsftp.js:171:8)
0|downspou |     at Stream.<anonymous> (/apps/seedbox-sync/htpc/node_modules/jsftp/lib/jsftp.js:139:10)
0|downspou |     at emitOne (events.js:96:13)
0|downspou |     at Stream.emit (events.js:188:7)
0|downspou |     at ResponseParser.reemit (/apps/seedbox-sync/htpc/node_modules/duplexer/index.js:70:25)
0|downspou |     at emitOne (events.js:96:13)
0|downspou |     at ResponseParser.emit (events.js:188:7)
0|downspou |     at readableAddChunk (/apps/seedbox-sync/htpc/node_modules/readable-stream/lib/_stream_readable.js:195:16)
0|downspou |     at ResponseParser.Readable.push (/apps/seedbox-sync/htpc/node_modules/readable-stream/lib/_stream_readable.js:162:10)
0|downspou |     at ResponseParser.Transform.push (/apps/seedbox-sync/htpc/node_modules/readable-stream/lib/_stream_transform.js:145:32)
0|downspou |     at ResponseParser.<anonymous> (/apps/seedbox-sync/htpc/node_modules/ftp-response-parser/index.js:62:12)
0|downspou |     at Array.forEach (native)
0|downspou |     at ResponseParser._transform (/apps/seedbox-sync/htpc/node_modules/ftp-response-parser/index.js:45:9)
0|downspou |     at ResponseParser.Transform._read (/apps/seedbox-sync/htpc/node_modules/readable-stream/lib/_stream_transform.js:184:10)
0|downspou |     at ResponseParser.Transform._write (/apps/seedbox-sync/htpc/node_modules/readable-stream/lib/_stream_transform.js:172:12)
0|downspou |     at doWrite (/apps/seedbox-sync/htpc/node_modules/readable-stream/lib/_stream_writable.js:279:12)```

**Comment by ThatOdieGuy** [comment]
I think I fixed this at some point.
